export const REACT_APP_SUPABASE_URL = process.env.REACT_APP_SUPABASE_URL
export const REACT_APP_SUPABASE_ANON_KEY =
  process.env.REACT_APP_SUPABASE_ANON_KEY
export const REACT_APP_SUPABASE_ADMIN_KEY =
  process.env.REACT_APP_SUPABASE_ADMIN_KEY
