TRUNCATE TABLE datapoints RESTART IDENTITY CASCADE;
TRUNCATE TABLE audits RESTART IDENTITY CASCADE;
TRUNCATE TABLE circle_kpi RESTART IDENTITY CASCADE;
TRUNCATE TABLE periods RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_circle RESTART IDENTITY CASCADE;
TRUNCATE TABLE circles RESTART IDENTITY CASCADE;
TRUNCATE TABLE kpis RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
