# Generated by Django 4.2.5 on 2023-10-05 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodicity",
            options={"verbose_name_plural": "Periodicities"},
        ),
    ]
