# Generated by Django 4.2.5 on 2023-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="circles",
            field=models.ManyToManyField(
                related_name="kpis", through="kpi_app.Circle_KPI", to="kpi_app.circle"
            ),
        ),
    ]
