# Generated by Django 4.2.5 on 2023-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0002_alter_kpi_circles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpi",
            name="circles",
        ),
        migrations.AddField(
            model_name="kpi",
            name="circle",
            field=models.ManyToManyField(
                through="kpi_app.Circle_KPI", to="kpi_app.circle"
            ),
        ),
    ]
