# Generated by Django 4.2.5 on 2023-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0002_alter_periodicity_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="period",
            name="year",
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name="periodicity",
            name="description",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="periodicity",
            name="type",
            field=models.CharField(
                choices=[("Y", "Yearly"), ("Q", "Quarterly"), ("M", "Monthly")]
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="display_value",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.CharField(max_length=50),
        ),
    ]
