# Generated by Django 4.2.5 on 2023-10-07 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0003_alter_circle_name_alter_period_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kpi",
            old_name="periodicity_id",
            new_name="periodicity",
        ),
        migrations.RenameField(
            model_name="kpi",
            old_name="range_id",
            new_name="range",
        ),
    ]
