# Generated by Django 4.2.5 on 2023-10-07 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0007_alter_period_month_alter_period_quarter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audit",
            old_name="circle_kpi_id",
            new_name="circle_kpi",
        ),
        migrations.RenameField(
            model_name="audit",
            old_name="period_id",
            new_name="period",
        ),
        migrations.RenameField(
            model_name="audit",
            old_name="user_id",
            new_name="user",
        ),
    ]
