# Generated by Django 4.2.5 on 2023-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kpi_app", "0008_rename_circle_kpi_id_audit_circle_kpi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
