Digital:
- additional monetization/savings from CRM
Fundraising:
- private donations
HR:
- share of teams constituted as circles
- share short tern leave
- involuntary headcount change (FTE)
Programs:
- additional monetization/savings from programs
Programs - Children - Counceling:
- reachability
Programs - Parents -Online:
- count sessions on .projuventute.ch
- count leads
- net promoter score
