create table "public"."audit" (
    "id" bigint generated by default as identity not null,
    "circle_kpi_id" bigint not null,
    "user_id" uuid not null,
    "period_id" bigint not null,
    "value" double precision not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."audit" enable row level security;

create table "public"."circle" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
);


alter table "public"."circle" enable row level security;

create table "public"."circle_kpi" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "circle_id" bigint,
    "kpi_id" bigint
);


alter table "public"."circle_kpi" enable row level security;

create table "public"."frequency" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" character varying not null,
    "description" character varying
);


alter table "public"."frequency" enable row level security;

create table "public"."kpi" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "sample_value" double precision not null,
    "description" character varying,
    "range_id" bigint not null,
    "frequency_id" bigint not null
);


alter table "public"."kpi" enable row level security;

create table "public"."period" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "year" bigint not null,
    "month" bigint,
    "quarter" bigint
);


alter table "public"."period" enable row level security;

create table "public"."range" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "min_value" double precision,
    "max_value" double precision,
    "display_value" character varying
);


alter table "public"."range" enable row level security;

create table "public"."user_circle" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "circle_id" bigint
);


alter table "public"."user_circle" enable row level security;

CREATE UNIQUE INDEX "Circle_pkey" ON public.circle USING btree (id);

CREATE UNIQUE INDEX "Frequency_pkey" ON public.frequency USING btree (id);

CREATE UNIQUE INDEX "Range_pkey" ON public.range USING btree (id);

CREATE UNIQUE INDEX audit_pkey ON public.audit USING btree (id);

CREATE UNIQUE INDEX circle_kpi_pkey ON public.circle_kpi USING btree (id);

CREATE UNIQUE INDEX kpi_pkey ON public.kpi USING btree (id);

CREATE UNIQUE INDEX period_pkey ON public.period USING btree (id);

CREATE UNIQUE INDEX user_circle_pkey ON public.user_circle USING btree (id);

alter table "public"."audit" add constraint "audit_pkey" PRIMARY KEY using index "audit_pkey";

alter table "public"."circle" add constraint "Circle_pkey" PRIMARY KEY using index "Circle_pkey";

alter table "public"."circle_kpi" add constraint "circle_kpi_pkey" PRIMARY KEY using index "circle_kpi_pkey";

alter table "public"."frequency" add constraint "Frequency_pkey" PRIMARY KEY using index "Frequency_pkey";

alter table "public"."kpi" add constraint "kpi_pkey" PRIMARY KEY using index "kpi_pkey";

alter table "public"."period" add constraint "period_pkey" PRIMARY KEY using index "period_pkey";

alter table "public"."range" add constraint "Range_pkey" PRIMARY KEY using index "Range_pkey";

alter table "public"."user_circle" add constraint "user_circle_pkey" PRIMARY KEY using index "user_circle_pkey";

alter table "public"."audit" add constraint "audit_circle_kpi_id_fkey" FOREIGN KEY (circle_kpi_id) REFERENCES circle_kpi(id) not valid;

alter table "public"."audit" validate constraint "audit_circle_kpi_id_fkey";

alter table "public"."audit" add constraint "audit_period_id_fkey" FOREIGN KEY (period_id) REFERENCES period(id) not valid;

alter table "public"."audit" validate constraint "audit_period_id_fkey";

alter table "public"."audit" add constraint "audit_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."audit" validate constraint "audit_user_id_fkey";

alter table "public"."circle_kpi" add constraint "circle_kpi_circle_id_fkey" FOREIGN KEY (circle_id) REFERENCES circle(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."circle_kpi" validate constraint "circle_kpi_circle_id_fkey";

alter table "public"."circle_kpi" add constraint "circle_kpi_kpi_id_fkey" FOREIGN KEY (kpi_id) REFERENCES kpi(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."circle_kpi" validate constraint "circle_kpi_kpi_id_fkey";

alter table "public"."kpi" add constraint "kpi_frequency_id_fkey" FOREIGN KEY (frequency_id) REFERENCES frequency(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."kpi" validate constraint "kpi_frequency_id_fkey";

alter table "public"."kpi" add constraint "kpi_range_id_fkey" FOREIGN KEY (range_id) REFERENCES range(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."kpi" validate constraint "kpi_range_id_fkey";

alter table "public"."user_circle" add constraint "user_circle_circle_id_fkey" FOREIGN KEY (circle_id) REFERENCES circle(id) not valid;

alter table "public"."user_circle" validate constraint "user_circle_circle_id_fkey";

alter table "public"."user_circle" add constraint "user_circle_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_circle" validate constraint "user_circle_user_id_fkey";