create schema if not exists "dev_schema";

create table "dev_schema"."auth_group" (
    "id" integer generated by default as identity not null,
    "name" character varying(150) not null
);


create table "dev_schema"."auth_group_permissions" (
    "id" bigint generated by default as identity not null,
    "group_id" integer not null,
    "permission_id" integer not null
);


create table "dev_schema"."auth_permission" (
    "id" integer generated by default as identity not null,
    "name" character varying(255) not null,
    "content_type_id" integer not null,
    "codename" character varying(100) not null
);


create table "dev_schema"."django_admin_log" (
    "id" integer generated by default as identity not null,
    "action_time" timestamp with time zone not null,
    "object_id" text,
    "object_repr" character varying(200) not null,
    "action_flag" smallint not null,
    "change_message" text not null,
    "content_type_id" integer,
    "user_id" bigint not null
);


create table "dev_schema"."django_content_type" (
    "id" integer generated by default as identity not null,
    "app_label" character varying(100) not null,
    "model" character varying(100) not null
);


create table "dev_schema"."django_migrations" (
    "id" bigint generated by default as identity not null,
    "app" character varying(255) not null,
    "name" character varying(255) not null,
    "applied" timestamp with time zone not null
);


create table "dev_schema"."django_session" (
    "session_key" character varying(40) not null,
    "session_data" text not null,
    "expire_date" timestamp with time zone not null
);


create table "dev_schema"."kpi_app_audit" (
    "id" bigint generated by default as identity not null,
    "value" numeric(16,2) not null,
    "created_timestamp" timestamp with time zone not null,
    "updated_timestamp" timestamp with time zone not null,
    "circle_kpi_id" bigint not null,
    "period_id" bigint not null,
    "user_id" bigint not null
);


create table "dev_schema"."kpi_app_circle" (
    "id" bigint generated by default as identity not null,
    "name" character varying(255) not null
);


create table "dev_schema"."kpi_app_circle_kpi" (
    "id" bigint generated by default as identity not null,
    "circles_id" bigint not null,
    "kpi_id" bigint not null
);


create table "dev_schema"."kpi_app_frequency" (
    "id" bigint generated by default as identity not null,
    "type" character varying not null,
    "description" character varying(150) not null
);


create table "dev_schema"."kpi_app_kpi" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "frequency_id" bigint not null,
    "range_id" bigint not null,
    "description" character varying(250) not null,
    "sample_value" numeric(16,2) not null
);


create table "dev_schema"."kpi_app_period" (
    "id" bigint generated by default as identity not null,
    "year" integer not null,
    "month" integer,
    "quarter" integer
);


create table "dev_schema"."kpi_app_range" (
    "id" bigint generated by default as identity not null,
    "min_value" numeric(8,2) not null,
    "max_value" numeric(8,2) not null,
    "display_value" character varying(255) not null
);


create table "dev_schema"."kpi_app_role" (
    "id" bigint generated by default as identity not null,
    "name" character varying(255) not null,
    "description" character varying(255) not null
);


create table "dev_schema"."kpi_app_user" (
    "id" bigint generated by default as identity not null,
    "password" character varying(128) not null,
    "last_login" timestamp with time zone,
    "is_superuser" boolean not null,
    "username" character varying(150) not null,
    "first_name" character varying(150) not null,
    "last_name" character varying(150) not null,
    "email" character varying(254) not null,
    "is_staff" boolean not null,
    "is_active" boolean not null,
    "date_joined" timestamp with time zone not null,
    "role_id" bigint
);


create table "dev_schema"."kpi_app_user_circle" (
    "id" bigint generated by default as identity not null,
    "circle_id" bigint not null,
    "user_id" bigint not null
);


create table "dev_schema"."kpi_app_user_groups" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "group_id" integer not null
);


create table "dev_schema"."kpi_app_user_user_permissions" (
    "id" bigint generated by default as identity not null,
    "user_id" bigint not null,
    "permission_id" integer not null
);


create table "dev_schema"."leaderboard" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "dev_schema"."leaderboard" enable row level security;

CREATE INDEX auth_group_name_a6ea08ec_like ON dev_schema.auth_group USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX auth_group_name_key ON dev_schema.auth_group USING btree (name);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON dev_schema.auth_group_permissions USING btree (group_id);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON dev_schema.auth_group_permissions USING btree (group_id, permission_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON dev_schema.auth_group_permissions USING btree (permission_id);

CREATE UNIQUE INDEX auth_group_permissions_pkey ON dev_schema.auth_group_permissions USING btree (id);

CREATE UNIQUE INDEX auth_group_pkey ON dev_schema.auth_group USING btree (id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON dev_schema.auth_permission USING btree (content_type_id);

CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON dev_schema.auth_permission USING btree (content_type_id, codename);

CREATE UNIQUE INDEX auth_permission_pkey ON dev_schema.auth_permission USING btree (id);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON dev_schema.django_admin_log USING btree (content_type_id);

CREATE UNIQUE INDEX django_admin_log_pkey ON dev_schema.django_admin_log USING btree (id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON dev_schema.django_admin_log USING btree (user_id);

CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON dev_schema.django_content_type USING btree (app_label, model);

CREATE UNIQUE INDEX django_content_type_pkey ON dev_schema.django_content_type USING btree (id);

CREATE UNIQUE INDEX django_migrations_pkey ON dev_schema.django_migrations USING btree (id);

CREATE INDEX django_session_expire_date_a5c62663 ON dev_schema.django_session USING btree (expire_date);

CREATE UNIQUE INDEX django_session_pkey ON dev_schema.django_session USING btree (session_key);

CREATE INDEX django_session_session_key_c0390e0f_like ON dev_schema.django_session USING btree (session_key varchar_pattern_ops);

CREATE INDEX kpi_app_audit_circle_kpi_id_0e19418e ON dev_schema.kpi_app_audit USING btree (circle_kpi_id);

CREATE INDEX kpi_app_audit_period_id_2b22ccff ON dev_schema.kpi_app_audit USING btree (period_id);

CREATE UNIQUE INDEX kpi_app_audit_pkey ON dev_schema.kpi_app_audit USING btree (id);

CREATE INDEX kpi_app_audit_user_id_0c730a00 ON dev_schema.kpi_app_audit USING btree (user_id);

CREATE INDEX kpi_app_circle_kpi_circles_id_aa4abbec ON dev_schema.kpi_app_circle_kpi USING btree (circles_id);

CREATE INDEX kpi_app_circle_kpi_kpi_id_f726f34c ON dev_schema.kpi_app_circle_kpi USING btree (kpi_id);

CREATE UNIQUE INDEX kpi_app_circle_kpi_pkey ON dev_schema.kpi_app_circle_kpi USING btree (id);

CREATE INDEX kpi_app_circle_name_71b6fc9d_like ON dev_schema.kpi_app_circle USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX kpi_app_circle_name_key ON dev_schema.kpi_app_circle USING btree (name);

CREATE UNIQUE INDEX kpi_app_circle_pkey ON dev_schema.kpi_app_circle USING btree (id);

CREATE INDEX kpi_app_kpi_name_f98df987_like ON dev_schema.kpi_app_kpi USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX kpi_app_kpi_name_key ON dev_schema.kpi_app_kpi USING btree (name);

CREATE INDEX kpi_app_kpi_periodicity_id_a8778d2d ON dev_schema.kpi_app_kpi USING btree (frequency_id);

CREATE UNIQUE INDEX kpi_app_kpi_pkey ON dev_schema.kpi_app_kpi USING btree (id);

CREATE INDEX kpi_app_kpi_range_id_8de87dce ON dev_schema.kpi_app_kpi USING btree (range_id);

CREATE UNIQUE INDEX kpi_app_period_pkey ON dev_schema.kpi_app_period USING btree (id);

CREATE UNIQUE INDEX kpi_app_periodicity_pkey ON dev_schema.kpi_app_frequency USING btree (id);

CREATE UNIQUE INDEX kpi_app_range_pkey ON dev_schema.kpi_app_range USING btree (id);

CREATE INDEX kpi_app_role_name_b56f109b_like ON dev_schema.kpi_app_role USING btree (name varchar_pattern_ops);

CREATE UNIQUE INDEX kpi_app_role_name_b56f109b_uniq ON dev_schema.kpi_app_role USING btree (name);

CREATE UNIQUE INDEX kpi_app_role_pkey ON dev_schema.kpi_app_role USING btree (id);

CREATE INDEX kpi_app_user_circle_circle_id_id_85c67dc1 ON dev_schema.kpi_app_user_circle USING btree (circle_id);

CREATE UNIQUE INDEX kpi_app_user_circle_pkey ON dev_schema.kpi_app_user_circle USING btree (id);

CREATE INDEX kpi_app_user_circle_user_id_id_1e2561c6 ON dev_schema.kpi_app_user_circle USING btree (user_id);

CREATE INDEX kpi_app_user_email_0aa79233_like ON dev_schema.kpi_app_user USING btree (email varchar_pattern_ops);

CREATE UNIQUE INDEX kpi_app_user_email_0aa79233_uniq ON dev_schema.kpi_app_user USING btree (email);

CREATE INDEX kpi_app_user_groups_group_id_8cb2d405 ON dev_schema.kpi_app_user_groups USING btree (group_id);

CREATE UNIQUE INDEX kpi_app_user_groups_pkey ON dev_schema.kpi_app_user_groups USING btree (id);

CREATE INDEX kpi_app_user_groups_user_id_487911c2 ON dev_schema.kpi_app_user_groups USING btree (user_id);

CREATE UNIQUE INDEX kpi_app_user_groups_user_id_group_id_6140bc4b_uniq ON dev_schema.kpi_app_user_groups USING btree (user_id, group_id);

CREATE UNIQUE INDEX kpi_app_user_pkey ON dev_schema.kpi_app_user USING btree (id);

CREATE INDEX kpi_app_user_role_id_id_a0e2af70 ON dev_schema.kpi_app_user USING btree (role_id);

CREATE UNIQUE INDEX kpi_app_user_user_permis_user_id_permission_id_cd5b8e2f_uniq ON dev_schema.kpi_app_user_user_permissions USING btree (user_id, permission_id);

CREATE INDEX kpi_app_user_user_permissions_permission_id_c4e38da0 ON dev_schema.kpi_app_user_user_permissions USING btree (permission_id);

CREATE UNIQUE INDEX kpi_app_user_user_permissions_pkey ON dev_schema.kpi_app_user_user_permissions USING btree (id);

CREATE INDEX kpi_app_user_user_permissions_user_id_dd9f0cc3 ON dev_schema.kpi_app_user_user_permissions USING btree (user_id);

CREATE INDEX kpi_app_user_username_3ab2b3d1_like ON dev_schema.kpi_app_user USING btree (username varchar_pattern_ops);

CREATE UNIQUE INDEX kpi_app_user_username_key ON dev_schema.kpi_app_user USING btree (username);

CREATE UNIQUE INDEX leaderboard_id_key ON dev_schema.leaderboard USING btree (id);

CREATE UNIQUE INDEX leaderboard_pkey ON dev_schema.leaderboard USING btree (id);

CREATE UNIQUE INDEX unique_range_definition ON dev_schema.kpi_app_range USING btree (min_value, max_value, display_value);

alter table "dev_schema"."auth_group" add constraint "auth_group_pkey" PRIMARY KEY using index "auth_group_pkey";

alter table "dev_schema"."auth_group_permissions" add constraint "auth_group_permissions_pkey" PRIMARY KEY using index "auth_group_permissions_pkey";

alter table "dev_schema"."auth_permission" add constraint "auth_permission_pkey" PRIMARY KEY using index "auth_permission_pkey";

alter table "dev_schema"."django_admin_log" add constraint "django_admin_log_pkey" PRIMARY KEY using index "django_admin_log_pkey";

alter table "dev_schema"."django_content_type" add constraint "django_content_type_pkey" PRIMARY KEY using index "django_content_type_pkey";

alter table "dev_schema"."django_migrations" add constraint "django_migrations_pkey" PRIMARY KEY using index "django_migrations_pkey";

alter table "dev_schema"."django_session" add constraint "django_session_pkey" PRIMARY KEY using index "django_session_pkey";

alter table "dev_schema"."kpi_app_audit" add constraint "kpi_app_audit_pkey" PRIMARY KEY using index "kpi_app_audit_pkey";

alter table "dev_schema"."kpi_app_circle" add constraint "kpi_app_circle_pkey" PRIMARY KEY using index "kpi_app_circle_pkey";

alter table "dev_schema"."kpi_app_circle_kpi" add constraint "kpi_app_circle_kpi_pkey" PRIMARY KEY using index "kpi_app_circle_kpi_pkey";

alter table "dev_schema"."kpi_app_frequency" add constraint "kpi_app_periodicity_pkey" PRIMARY KEY using index "kpi_app_periodicity_pkey";

alter table "dev_schema"."kpi_app_kpi" add constraint "kpi_app_kpi_pkey" PRIMARY KEY using index "kpi_app_kpi_pkey";

alter table "dev_schema"."kpi_app_period" add constraint "kpi_app_period_pkey" PRIMARY KEY using index "kpi_app_period_pkey";

alter table "dev_schema"."kpi_app_range" add constraint "kpi_app_range_pkey" PRIMARY KEY using index "kpi_app_range_pkey";

alter table "dev_schema"."kpi_app_role" add constraint "kpi_app_role_pkey" PRIMARY KEY using index "kpi_app_role_pkey";

alter table "dev_schema"."kpi_app_user" add constraint "kpi_app_user_pkey" PRIMARY KEY using index "kpi_app_user_pkey";

alter table "dev_schema"."kpi_app_user_circle" add constraint "kpi_app_user_circle_pkey" PRIMARY KEY using index "kpi_app_user_circle_pkey";

alter table "dev_schema"."kpi_app_user_groups" add constraint "kpi_app_user_groups_pkey" PRIMARY KEY using index "kpi_app_user_groups_pkey";

alter table "dev_schema"."kpi_app_user_user_permissions" add constraint "kpi_app_user_user_permissions_pkey" PRIMARY KEY using index "kpi_app_user_user_permissions_pkey";

alter table "dev_schema"."leaderboard" add constraint "leaderboard_pkey" PRIMARY KEY using index "leaderboard_pkey";

alter table "dev_schema"."auth_group" add constraint "auth_group_name_key" UNIQUE using index "auth_group_name_key";

alter table "dev_schema"."auth_group_permissions" add constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES dev_schema.auth_permission(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."auth_group_permissions" validate constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm";

alter table "dev_schema"."auth_group_permissions" add constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES dev_schema.auth_group(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."auth_group_permissions" validate constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id";

alter table "dev_schema"."auth_group_permissions" add constraint "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE using index "auth_group_permissions_group_id_permission_id_0cd325b0_uniq";

alter table "dev_schema"."auth_permission" add constraint "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES dev_schema.django_content_type(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."auth_permission" validate constraint "auth_permission_content_type_id_2f476e4b_fk_django_co";

alter table "dev_schema"."auth_permission" add constraint "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE using index "auth_permission_content_type_id_codename_01ab375a_uniq";

alter table "dev_schema"."django_admin_log" add constraint "django_admin_log_action_flag_check" CHECK ((action_flag >= 0)) not valid;

alter table "dev_schema"."django_admin_log" validate constraint "django_admin_log_action_flag_check";

alter table "dev_schema"."django_admin_log" add constraint "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES dev_schema.django_content_type(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."django_admin_log" validate constraint "django_admin_log_content_type_id_c4bce8eb_fk_django_co";

alter table "dev_schema"."django_admin_log" add constraint "django_admin_log_user_id_c564eba6_fk_kpi_app_user_id" FOREIGN KEY (user_id) REFERENCES dev_schema.kpi_app_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."django_admin_log" validate constraint "django_admin_log_user_id_c564eba6_fk_kpi_app_user_id";

alter table "dev_schema"."django_content_type" add constraint "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE using index "django_content_type_app_label_model_76bd3d3b_uniq";

alter table "dev_schema"."kpi_app_audit" add constraint "kpi_app_audit_circle_kpi_id_0e19418e_fk_kpi_app_circle_kpi_id" FOREIGN KEY (circle_kpi_id) REFERENCES dev_schema.kpi_app_circle_kpi(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_audit" validate constraint "kpi_app_audit_circle_kpi_id_0e19418e_fk_kpi_app_circle_kpi_id";

alter table "dev_schema"."kpi_app_audit" add constraint "kpi_app_audit_period_id_2b22ccff_fk_kpi_app_period_id" FOREIGN KEY (period_id) REFERENCES dev_schema.kpi_app_period(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_audit" validate constraint "kpi_app_audit_period_id_2b22ccff_fk_kpi_app_period_id";

alter table "dev_schema"."kpi_app_audit" add constraint "kpi_app_audit_user_id_0c730a00_fk_kpi_app_user_id" FOREIGN KEY (user_id) REFERENCES dev_schema.kpi_app_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_audit" validate constraint "kpi_app_audit_user_id_0c730a00_fk_kpi_app_user_id";

alter table "dev_schema"."kpi_app_circle" add constraint "kpi_app_circle_name_key" UNIQUE using index "kpi_app_circle_name_key";

alter table "dev_schema"."kpi_app_circle_kpi" add constraint "kpi_app_circle_kpi_circles_id_aa4abbec_fk_kpi_app_circle_id" FOREIGN KEY (circles_id) REFERENCES dev_schema.kpi_app_circle(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_circle_kpi" validate constraint "kpi_app_circle_kpi_circles_id_aa4abbec_fk_kpi_app_circle_id";

alter table "dev_schema"."kpi_app_circle_kpi" add constraint "kpi_app_circle_kpi_kpi_id_f726f34c_fk_kpi_app_kpi_id" FOREIGN KEY (kpi_id) REFERENCES dev_schema.kpi_app_kpi(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_circle_kpi" validate constraint "kpi_app_circle_kpi_kpi_id_f726f34c_fk_kpi_app_kpi_id";

alter table "dev_schema"."kpi_app_kpi" add constraint "kpi_app_kpi_frequency_id_a25d6efc_fk_kpi_app_frequency_id" FOREIGN KEY (frequency_id) REFERENCES dev_schema.kpi_app_frequency(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_kpi" validate constraint "kpi_app_kpi_frequency_id_a25d6efc_fk_kpi_app_frequency_id";

alter table "dev_schema"."kpi_app_kpi" add constraint "kpi_app_kpi_name_key" UNIQUE using index "kpi_app_kpi_name_key";

alter table "dev_schema"."kpi_app_kpi" add constraint "kpi_app_kpi_range_id_8de87dce_fk_kpi_app_range_id" FOREIGN KEY (range_id) REFERENCES dev_schema.kpi_app_range(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_kpi" validate constraint "kpi_app_kpi_range_id_8de87dce_fk_kpi_app_range_id";

alter table "dev_schema"."kpi_app_range" add constraint "unique_range_definition" UNIQUE using index "unique_range_definition";

alter table "dev_schema"."kpi_app_role" add constraint "kpi_app_role_name_b56f109b_uniq" UNIQUE using index "kpi_app_role_name_b56f109b_uniq";

alter table "dev_schema"."kpi_app_user" add constraint "kpi_app_user_email_0aa79233_uniq" UNIQUE using index "kpi_app_user_email_0aa79233_uniq";

alter table "dev_schema"."kpi_app_user" add constraint "kpi_app_user_role_id_8b6dd29b_fk_kpi_app_role_id" FOREIGN KEY (role_id) REFERENCES dev_schema.kpi_app_role(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user" validate constraint "kpi_app_user_role_id_8b6dd29b_fk_kpi_app_role_id";

alter table "dev_schema"."kpi_app_user" add constraint "kpi_app_user_username_key" UNIQUE using index "kpi_app_user_username_key";

alter table "dev_schema"."kpi_app_user_circle" add constraint "kpi_app_user_circle_circle_id_da1a9a6b_fk_kpi_app_circle_id" FOREIGN KEY (circle_id) REFERENCES dev_schema.kpi_app_circle(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_circle" validate constraint "kpi_app_user_circle_circle_id_da1a9a6b_fk_kpi_app_circle_id";

alter table "dev_schema"."kpi_app_user_circle" add constraint "kpi_app_user_circle_user_id_ba4b7680_fk_kpi_app_user_id" FOREIGN KEY (user_id) REFERENCES dev_schema.kpi_app_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_circle" validate constraint "kpi_app_user_circle_user_id_ba4b7680_fk_kpi_app_user_id";

alter table "dev_schema"."kpi_app_user_groups" add constraint "kpi_app_user_groups_group_id_8cb2d405_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES dev_schema.auth_group(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_groups" validate constraint "kpi_app_user_groups_group_id_8cb2d405_fk_auth_group_id";

alter table "dev_schema"."kpi_app_user_groups" add constraint "kpi_app_user_groups_user_id_487911c2_fk_kpi_app_user_id" FOREIGN KEY (user_id) REFERENCES dev_schema.kpi_app_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_groups" validate constraint "kpi_app_user_groups_user_id_487911c2_fk_kpi_app_user_id";

alter table "dev_schema"."kpi_app_user_groups" add constraint "kpi_app_user_groups_user_id_group_id_6140bc4b_uniq" UNIQUE using index "kpi_app_user_groups_user_id_group_id_6140bc4b_uniq";

alter table "dev_schema"."kpi_app_user_user_permissions" add constraint "kpi_app_user_user_pe_permission_id_c4e38da0_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES dev_schema.auth_permission(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_user_permissions" validate constraint "kpi_app_user_user_pe_permission_id_c4e38da0_fk_auth_perm";

alter table "dev_schema"."kpi_app_user_user_permissions" add constraint "kpi_app_user_user_pe_user_id_dd9f0cc3_fk_kpi_app_u" FOREIGN KEY (user_id) REFERENCES dev_schema.kpi_app_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "dev_schema"."kpi_app_user_user_permissions" validate constraint "kpi_app_user_user_pe_user_id_dd9f0cc3_fk_kpi_app_u";

alter table "dev_schema"."kpi_app_user_user_permissions" add constraint "kpi_app_user_user_permis_user_id_permission_id_cd5b8e2f_uniq" UNIQUE using index "kpi_app_user_user_permis_user_id_permission_id_cd5b8e2f_uniq";

alter table "dev_schema"."leaderboard" add constraint "leaderboard_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "dev_schema"."leaderboard" validate constraint "leaderboard_id_fkey";

alter table "dev_schema"."leaderboard" add constraint "leaderboard_id_key" UNIQUE using index "leaderboard_id_key";


create schema if not exists "kpi_app";


create schema if not exists "prod_schema";


create sequence "public"."circle_kpi_id_seq";

drop policy "Enable ALL privileges to GK" on "public"."kpi";

drop policy "Enable read access to the Economist" on "public"."kpi";

alter table "public"."kpi" drop constraint "kpi_id_key";

alter table "public"."audit" drop constraint "audit_period_id_fkey";

alter table "public"."audit" drop constraint "audit_user_id_fkey";

alter table "public"."circle_kpi" drop constraint "circle_kpi_kpi_id_fkey";

alter table "public"."circle_kpi" drop constraint "kpi_circle_pkey";

drop index if exists "public"."kpi_circle_pkey";

drop index if exists "public"."kpi_id_key";

alter table "public"."audit" alter column "circle_kpi_id" set data type integer using "circle_kpi_id"::integer;

alter table "public"."audit" alter column "id" set generated always;

alter table "public"."audit" alter column "period_id" set data type integer using "period_id"::integer;

alter table "public"."audit" alter column "value" set not null;

alter table "public"."audit" alter column "value" set data type bigint using "value"::bigint;

alter table "public"."audit" disable row level security;

alter table "public"."circle_kpi" drop column "created_at";

alter table "public"."circle_kpi" add column "id" integer not null default nextval('circle_kpi_id_seq'::regclass);

alter table "public"."circle_kpi" alter column "kpi_id" set data type bigint using "kpi_id"::bigint;

alter sequence "public"."circle_kpi_id_seq" owned by "public"."circle_kpi"."id";

CREATE UNIQUE INDEX circle_kpi_pkey ON public.circle_kpi USING btree (id, circle_id, kpi_id);

CREATE UNIQUE INDEX unique_kpi_constraint ON public.kpi USING btree (name);

CREATE UNIQUE INDEX unique_range_constraint ON public.range USING btree (min_value, max_value, display_value);

alter table "public"."circle_kpi" add constraint "circle_kpi_pkey" PRIMARY KEY using index "circle_kpi_pkey";

alter table "public"."kpi" add constraint "unique_kpi_constraint" UNIQUE using index "unique_kpi_constraint";

alter table "public"."range" add constraint "unique_range_constraint" UNIQUE using index "unique_range_constraint";

alter table "public"."audit" add constraint "audit_period_id_fkey" FOREIGN KEY (period_id) REFERENCES period(id) not valid;

alter table "public"."audit" validate constraint "audit_period_id_fkey";

alter table "public"."audit" add constraint "audit_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."audit" validate constraint "audit_user_id_fkey";

alter table "public"."circle_kpi" add constraint "circle_kpi_kpi_id_fkey" FOREIGN KEY (kpi_id) REFERENCES kpi(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."circle_kpi" validate constraint "circle_kpi_kpi_id_fkey";

create policy "Enable ALL access for Gatekeeper"
on "public"."circle_kpi"
as permissive
for all
to gatekeeper
using (true)
with check (true);


create policy "Enable ALL access for Gatekeeper"
on "public"."kpi"
as permissive
for all
to gatekeeper
using (true)
with check (true);


create policy "Enable SELECT access for economist"
on "public"."kpi"
as permissive
for select
to economist
using (check_circle(auth.uid(), id));



