name: Deploy to DEV
on:
  push:
    branches:
      - dev01
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          REACT_APP_SUPABASE_ADMIN_KEY: ${{ secrets.REACT_APP_SUPABASE_ADMIN_KEY }}
