name: Deploy to DEV
on:
  push:
    branches:
      - dev01

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create environment file
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" > .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> .env
          echo "REACT_APP_SUPABASE_ADMIN_KEY=${{ secrets.REACT_APP_SUPABASE_ADMIN_KEY }}" >> .env
          echo "REACT_APP_PUBLIC_SITE_URL=${{ secrets.REACT_APP_PUBLIC_SITE_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        env:
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
          REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
          REACT_APP_SUPABASE_ADMIN_KEY: ${{ secrets.REACT_APP_SUPABASE_ADMIN_KEY }}
          REACT_APP_PUBLIC_SITE_URL: ${{ secrets.REACT_APP_PUBLIC_SITE_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only --config ./fly.development.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Clean up environment file
        run: |
          rm .env
